### ISSUE TITLE
debugpy install fail on Windows

### ISSUE THREAD

**Issue by sho-87** [williamboman/mason.nvim#1071]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Trying to install debugpy via mason, and also automatically via [mason-nvim-dap](https://github.com/jay-babu/mason-nvim-dap.nvim). In both cases, the installation fails with an error

I have setup a venv with debugpy installed. Have also tested this with a conda env with debugpy, but both end up with the same error

mason-nvim-dap dot, if relevant: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/mason-dap.lua

### Expected behavior

Installation to succeed without error

### Affected packages

debugpy

### Mason output

```Text
Failed
    ◍ debugpy
      ▼ Displaying full log
        Collecting debugpy
          Using cached debugpy-1.6.6-cp310-cp310-win_amd64.whl (4.8 MB)
        Installing collected packages: debugpy
        Successfully installed debugpy-1.6.6
        Cannot write Python exec wrapper for module "debugpy" as it doesn't exist.
```
```


### Installation log

```Text
[DEBUG 2023-03-06 1:09:46 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 21900
[DEBUG 2023-03-06 1:09:46 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=31592 exited with exit_code=0, signal=0
[DEBUG 2023-03-06 1:09:46 AM] ...lazy/mason.nvim/lua/mason-core/package/version-check.lua:72: Version check failed Primary package is not outdated.
[DEBUG 2023-03-06 1:09:46 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=21900 exited with exit_code=0, signal=0
[DEBUG 2023-03-06 1:09:46 AM] ...lazy/mason.nvim/lua/mason-core/package/version-check.lua:72: Version check failed Primary package is not outdated.
[DEBUG 2023-03-06 1:09:47 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=11776 exited with exit_code=0, signal=0
[DEBUG 2023-03-06 1:09:47 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="python", spawn_opts={
  args = { "-m", "pip", "--disable-pip-version-check", "install", "-U", "debugpy" },
  cwd = "C:\\Users\\Simon\\AppData\\Local\\nvim-data\\mason\\packages\\debugpy",
  env = { "SYSTEMDRIVE=<redacted>", "LOGONSERVER=<redacted>", "WT_PROFILE_ID=<redacted>", "POSH_THEME=<redacted>", "COMMONPROGRAMFILES(X86)=<redacted>", "USERNAME=<redacted>", "CUDA_PATH=<redacted>", "PSMODULEPATH=<redacted>", "COMPUTERNAME=<redacted>", "NVTOOLSEXT_PATH=<redacted>", "NVCUDASAMPLES_ROOT=<redacted>", "POSH_THEMES_PATH=<redacted>", "CHOCOLATEYINSTALL=<redacted>", "HOMEDRIVE=<redacted>", "COMSPEC=<redacted>", "RLSSVCPORT=<redacted>", "ACSVCPORT=<redacted>", "MYVIMRC=<redacted>", "POSH_PID=<redacted>", "PROCESSOR_ARCHITECTURE=<redacted>", "USERDOMAIN_ROAMINGPROFILE=<redacted>", "ONEDRIVECONSUMER=<redacted>", "COMMONPROGRAMW6432=<redacted>", "PATHEXT=<redacted>", "LOCALAPPDATA=<redacted>", "POSH_CURSOR_LINE=<redacted>", "POSH_GIT_ENABLED=<redacted>", "TMP=<redacted>", "USERDOMAIN=<redacted>", "PROCESSOR_REVISION=<redacted>", "ALLUSERSPROFILE=<redacted>", "CHOCOLATEYLASTPATHUPDATE=<redacted>", "VIMRUNTIME=<redacted>", "PROCESSOR_LEVEL=<redacted>", "SYSTEMROOT=<redacted>", "CONDA_PROMPT_MODIFIER=<redacted>", "WT_SESSION=<redacted>", "NVIM_LOG_FILE=<redacted>", "DRIVERDATA=<redacted>", "POSH_CURSOR_COLUMN=<redacted>", "PROGRAMW6432=<redacted>", "TERM=<redacted>", "WINDIR=<redacted>", "WSLENV=<redacted>", "PROCESSOR_IDENTIFIER=<redacted>", "OS=<redacted>", "CUDA_PATH_V11_5=<redacted>", "TEMP=<redacted>", "NUMBER_OF_PROCESSORS=<redacted>", "PUBLIC=<redacted>", "PROGRAMFILES=<redacted>", "ONEDRIVE=<redacted>", "POWERLINE_COMMAND=<redacted>", "MASON=<redacted>", "POSH_AZURE_ENABLED=<redacted>", "USERPROFILE=<redacted>", "PROGRAMFILES(X86)=<redacted>", "APPDATA=<redacted>", "PROGRAMDATA=<redacted>", "NVCUDASAMPLES11_5_ROOT=<redacted>", "VIM=<redacted>", "HOMEPATH=<redacted>", "COMMONPROGRAMFILES=<redacted>", "PATH=C:\\Users\\Simon\\AppData\\Local\\nvim-data\\mason\\packages\\debugpy\\venv\\Scripts;C:\\Users\\Simon\\AppData\\Local\\nvim-data\\mason\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.5\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.5\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Calibre2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\dotnet\\;C:\\Program Files\\CMake\\bin;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2021.3.1\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\nodejs\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Neovim\\bin;C:\\Program Files\\Neovide\\;C:\\Program Files\\Neovim;C:\\Users\\Simon\\AppData\\Local\\Programs\\oh-my-posh\\bin;C:\\Users\\Simon\\miniconda3\\Scripts;C:\\Users\\Simon\\miniconda3\\bin;C:\\Users\\Simon\\miniconda3;C:\\Tools\\ripgrep\\;C:\\Tools\\lazygit\\;C:\\Tools\\w64devkit\\bin;C:\\Users\\Simon\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\Neovim\\bin" }
}
[DEBUG 2023-03-06 1:09:47 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 20548
[DEBUG 2023-03-06 1:09:49 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=20548 exited with exit_code=0, signal=0
[DEBUG 2023-03-06 1:09:49 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="python", spawn_opts={
  args = { "-c", "import debugpy" },
  cwd = "C:\\Users\\Simon\\AppData\\Local\\nvim-data\\mason\\packages\\debugpy",
  env = { "SYSTEMDRIVE=<redacted>", "LOGONSERVER=<redacted>", "WT_PROFILE_ID=<redacted>", "POSH_THEME=<redacted>", "COMMONPROGRAMFILES(X86)=<redacted>", "USERNAME=<redacted>", "CUDA_PATH=<redacted>", "PSMODULEPATH=<redacted>", "COMPUTERNAME=<redacted>", "NVTOOLSEXT_PATH=<redacted>", "NVCUDASAMPLES_ROOT=<redacted>", "POSH_THEMES_PATH=<redacted>", "CHOCOLATEYINSTALL=<redacted>", "HOMEDRIVE=<redacted>", "COMSPEC=<redacted>", "RLSSVCPORT=<redacted>", "ACSVCPORT=<redacted>", "MYVIMRC=<redacted>", "POSH_PID=<redacted>", "PROCESSOR_ARCHITECTURE=<redacted>", "USERDOMAIN_ROAMINGPROFILE=<redacted>", "ONEDRIVECONSUMER=<redacted>", "COMMONPROGRAMW6432=<redacted>", "PATHEXT=<redacted>", "LOCALAPPDATA=<redacted>", "POSH_CURSOR_LINE=<redacted>", "POSH_GIT_ENABLED=<redacted>", "TMP=<redacted>", "USERDOMAIN=<redacted>", "PROCESSOR_REVISION=<redacted>", "ALLUSERSPROFILE=<redacted>", "CHOCOLATEYLASTPATHUPDATE=<redacted>", "VIMRUNTIME=<redacted>", "PROCESSOR_LEVEL=<redacted>", "SYSTEMROOT=<redacted>", "CONDA_PROMPT_MODIFIER=<redacted>", "WT_SESSION=<redacted>", "NVIM_LOG_FILE=<redacted>", "DRIVERDATA=<redacted>", "POSH_CURSOR_COLUMN=<redacted>", "PROGRAMW6432=<redacted>", "TERM=<redacted>", "WINDIR=<redacted>", "WSLENV=<redacted>", "PROCESSOR_IDENTIFIER=<redacted>", "OS=<redacted>", "CUDA_PATH_V11_5=<redacted>", "TEMP=<redacted>", "NUMBER_OF_PROCESSORS=<redacted>", "PUBLIC=<redacted>", "PROGRAMFILES=<redacted>", "ONEDRIVE=<redacted>", "POWERLINE_COMMAND=<redacted>", "MASON=<redacted>", "POSH_AZURE_ENABLED=<redacted>", "USERPROFILE=<redacted>", "PROGRAMFILES(X86)=<redacted>", "APPDATA=<redacted>", "PROGRAMDATA=<redacted>", "NVCUDASAMPLES11_5_ROOT=<redacted>", "VIM=<redacted>", "HOMEPATH=<redacted>", "COMMONPROGRAMFILES=<redacted>", "PATH=C:\\Users\\Simon\\AppData\\Local\\nvim-data\\mason\\packages\\debugpy\\venv\\Scripts;C:\\Users\\Simon\\AppData\\Local\\nvim-data\\mason\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.5\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.5\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Calibre2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\dotnet\\;C:\\Program Files\\CMake\\bin;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2021.3.1\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\nodejs\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Neovim\\bin;C:\\Program Files\\Neovide\\;C:\\Program Files\\Neovim;C:\\Users\\Simon\\AppData\\Local\\Programs\\oh-my-posh\\bin;C:\\Users\\Simon\\miniconda3\\Scripts;C:\\Users\\Simon\\miniconda3\\bin;C:\\Users\\Simon\\miniconda3;C:\\Tools\\ripgrep\\;C:\\Tools\\lazygit\\;C:\\Tools\\w64devkit\\bin;C:\\Users\\Simon\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\Neovim\\bin" }
}
[DEBUG 2023-03-06 1:09:49 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 7968
[DEBUG 2023-03-06 1:09:49 AM] ...cal/nvim-data/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=7968 exited with exit_code=0, signal=0
[ERROR 2023-03-06 1:09:49 AM] ...ata/lazy/mason.nvim/lua/mason-core/installer/context.lua:277: Failed to find module "\"debugpy\"" for package "Package(name=debugpy)". "...ata/lazy/mason.nvim/lua/mason-core/installer/context.lua:273: attempt to call method 'get_or_throw' (a nil value)"
[ERROR 2023-03-06 1:09:49 AM] ...m-data/lazy/mason.nvim/lua/mason-core/installer/init.lua:194: Installation failed for Package(name=debugpy) error="Cannot write Python exec wrapper for module \"debugpy\" as it doesn't exist."
[DEBUG 2023-03-06 1:09:49 AM] ...ta/Local/nvim-data/lazy/mason.nvim/lua/mason-core/fs.lua:47: fs: rmrf C:\Users\Simon\AppData\Local\nvim-data\mason\packages\debugpy
[DEBUG 2023-03-06 1:09:49 AM] ...m-data/lazy/mason.nvim/lua/mason-core/installer/init.lua:39: Building receipt for Package(name=debugpy)
[DEBUG 2023-03-06 1:09:49 AM] ...data/lazy/mason.nvim/lua/mason-core/installer/linker.lua:42: Unlinking Package(name=debugpy)
```
```


### Neovim version (>= 0.7)

NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Windows 11

### Healthcheck

```Text
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.11.0`
  - OK: **node**: `v16.15.1
`
  - WARNING: **python3**: not available
  - WARNING: **pip3**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
  - OK: **gzip**: `gzip 1.11`
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6 
`
  - ERROR: **pwsh**: not available
  - OK: **python**: `Python 3.10.9
`
  - OK: **pip**: `pip 22.3.1 from C:\Users\Simon\miniconda3\lib\site-packages\pip (python 3.10)

`
  - OK: **7z**: `7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: 2023-03-06 2:18:57 AM.
```

**Comment by williamboman** [comment]
Woops! Faulty logic due to recent refactor, should be fixed in #1073.

**Comment by oh-mycode** [comment]
What if I still have the same issue on MacOS too, even though I updated the mason plugin?

**Comment by oh-mycode** [comment]
> What if I still have the same issue on MacOS too, even though I updated the mason plugin?

nevermind, everything work, probably I didn't restart neovim when I tried at the first after update
