### ISSUE TITLE
setting sumneko up

### ISSUE THREAD

**Issue by bryant-the-coder** [williamboman/mason.nvim#124]
how to set sumneko up? it keeps saying cant find executable

**Comment by bryant-the-coder** [comment]
i have installed sumneko. but it cant find the path

**Comment by abderrahmane-tj** [comment]
What have you tried, and what errors (if any?) are you seeing?

**Comment by bryant-the-coder** [comment]
![image](https://user-images.githubusercontent.com/92417638/180667493-e921a987-a0ac-46be-ba50-b281955716be.png)

**Comment by bryant-the-coder** [comment]
```lua
-- sumneko_lua
local sumneko = {
    on_attach = on_attach,
    capabilities = capabilities,
    settings = {
        Lua = {
            diagnostics = {
                globals = { "vim" },
            },
            workspace = {
                library = {
                    [vim.fn.expand "$VIMRUNTIME/lua"] = true,
                    [vim.fn.stdpath "config" .. "/lua"] = true,
                },
            },
            hint = {
                enable = true,
                arrayIndex = "Enable", -- "Enable", "Auto", "Disable"
                await = true,
                paramName = "All", -- "All", "Literal", "Disable"
                paramType = true,
                semicolon = "All", -- "All", "SameLine", "Disable"
                setType = true,
            },
        },
    },
}
local use_lua_dev = true
if use_lua_dev then
    local luadev = require("lua-dev").setup {
        library = {
            vimruntime = true,
            types = true,
            plugins = { "nvim-treesitter", "plenary.nvim", "telescope.nvim" },
        },
        lspconfig = sumneko,
    }

    lspconfig.sumneko_lua.setup(luadev)
else
    lspconfig.sumneko_lua.setup(sumneko)
end
```

**Comment by bryant-the-coder** [comment]
other language servers work perfectly. (i am on windows)

**Comment by williamboman** [comment]
Since you're using `lspconfig` to set up servers, please make sure to use https://github.com/williamboman/mason-lspconfig.nvim

**Comment by benomine** [comment]
I just moved to mason and in order to make it work (everything is installed smoothly btw), I had to overwrite the cmd when trying to setup some of the lsp servers (like sumneko for example)

`
require('lspconfig')
local lsp_servers_path = vim.fn.stdpath('data') .. '/mason/packages'
`
and then (after defining the capabilities and all the stuff):
`
cmd = { sumneko_path_bin .. 'lua-language-server.exe', '-E', sumneko_path_bin .. '/main.lua' };
`

maybe not the intended way, but it works.

**Comment by bryant-the-coder** [comment]
> Since you're using `lspconfig` to set up servers, please make sure to use https://github.com/williamboman/mason-lspconfig.nvim

i installed it and lazyloaded it

**Comment by williamboman** [comment]
Cool! Remember to use one of the [issue templates](https://github.com/williamboman/mason.nvim/issues/new/choose) in the future, clearly stating (i) what isn't working, (ii) what you've done to try to fix it yourself, (iii) why you believe it's an error with the plugin, and (iiii) any additional information (providing more information early on helps everyone involved)

**Comment by williamboman** [comment]
I found an issue in mason-lspconfig where executables were not always expanded properly on Windows, fixed in https://github.com/williamboman/mason-lspconfig.nvim/pull/7. Might be related to your issues

**Comment by benomine** [comment]
I'm so dumb ahah.
It did not work at first because I called the lspconfig before calling mason and mason-lspconfig.
Now everything is working great and the code needed to call each and every lsp is just simpler. Thanks

**Comment by re-kaptcha** [comment]
I'm still facing this issue but with `mason-tool-installer`. I'm not using `mason-lspconfig` yet because I need to auto-install other tools. The following shows up when I run `:MasonLog`:
![image](https://user-images.githubusercontent.com/50426223/181344576-c931628f-20de-41e3-b0ca-e7fefa021738.png)

**Comment by re-kaptcha** [comment]
I ended up adding Mason's binary path to $PATH in order for it to work out of the box. Not ideal, but it works.

**Comment by williamboman** [comment]
@re-kaptcha I checked your dotfiles and it seems like you’re relying on Neovims builtin runtime file loading. It will load your files in after/plugin/ in alphabetical order. You have to make sure Mason setup executes before you set up lspconfig servers.

**Comment by re-kaptcha** [comment]
@williamboman Thanks for the tip. I moved Mason's configuration into the lua directory, then called it in my lspconfig setup before initializing the servers. I thought letting making packer load Mason after lspconfig would work, but apparently not. Thanks again.
